# Generated by Django 4.2.2 on 2023-07-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrisApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_with_boundaries',
            field=models.ImageField(blank=True, upload_to='photos/with_boundaries/'),
        ),
    ]
